name: SonarCloud Analysis

on:
  push:
  pull_request:

jobs:
  sonarQube:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      # Step 3: SonarCloud Scan with CI mode
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Mattheo4427_app-ios-awi
            -Dsonar.sources=.
            -Dsonar.java.binaries=.
            -Dsonar.scm.provider=git
            -Dsonar.qualitygate.wait=true